//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.WorkQueue {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class WorkQueue {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl message_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSAScheduled;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSATask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.GridView grdMSARecommendationTask;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(WorkQueue target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmessage_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.message_div = @__ctrl;
            @__ctrl.ID = "message_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "messageDiv");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n        "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSAScheduled() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSAScheduled = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSAScheduled";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSATask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSATask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSATask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrdMSARecommendationTask() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            this.grdMSARecommendationTask = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "grdMSARecommendationTask";
            @__ctrl.AutoGenerateColumns = false;
            @__ctrl.CssClass = "GridViewStyle";
            @__ctrl.GridLines = global::System.Web.UI.WebControls.GridLines.Both;
            @__ctrl.HeaderStyle.BackColor = global::System.Drawing.Color.AliceBlue;
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            @__ctrl.CellPadding = 10;
            @__ctrl.CellSpacing = 10;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.WorkQueue.WorkQueue @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n<link href=\"/_layouts/15/SL.FG.FFL/CSS/FGStyle.css\" rel=\"stylesheet\" />\r\n\r\n" +
                        "<div class=\"container\">\r\n    <div class=\"row\">\r\n        "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlmessage_div();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA Schedule</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse3"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse3"" class=""panel-collapse collapse"">
                    <div class=""panel-body""  style=""height: 200px; overflow-y:scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput3"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            @__ctrl2 = this.@__BuildControlgrdMSAScheduled();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA (Saved as draft)</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse1"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse1"" class=""panel-collapse collapse"">
                    <div class=""panel-body"" style=""height: 200px; overflow-y:scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput1"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl3;
            @__ctrl3 = this.@__BuildControlgrdMSATask();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class=""col-lg-12"">
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <div class=""row"">
                        <div class=""col-lg-9"">
                            <h5>MSA Recommendation</h5>
                        </div>
                        <div class=""col-lg-3"">
                            <span class=""panel-title pull-right""
                                data-toggle=""collapse""
                                data-target=""#collapse2"">
                                <i class='glyphicon glyphicon-sort'></i>
                            </span>
                        </div>
                    </div>
                </div>
                <div id=""collapse2"" class=""panel-collapse collapse"">
                    <div class=""panel-body""  style=""height: 200px; overflow-y:scroll;"">
                        <div class=""row"">
                            <div style=""margin: 10px;"">
                                <input type=""text"" id=""searchInput2"" placeholder=""Search..."" class=""form-control"" />
                            </div>
                        </div>
                        <div class=""row"">
                            <div class=""col-lg-12"">
                                "));
            global::System.Web.UI.WebControls.GridView @__ctrl4;
            @__ctrl4 = this.@__BuildControlgrdMSARecommendationTask();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/jQuery.js""></script>

<script src=""/_layouts/15/SL.FG.FFL/Scripts/WorkQueue/WorkQueue.js""></script>



"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
