//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL.FG.FFL.WebParts.MSARecommendationForm {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class MSARecommendationForm {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl message_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText recommendationNo_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.DropDownList approvalAuthority_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea description_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText targetDate_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.PeopleEditor responsiblePerson_PeopleEditor;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText responsibleDepartment_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText responsibleSection_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlSelect status_ddl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText injuryClassification_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText typeOfVoilation_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText observationCategoryA_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea lastStatement_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTextArea closureJustification_ta;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::Microsoft.SharePoint.WebControls.DateTimeControl closureDate_dtc;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText initiatedBy_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlInputText approvedBy_tf;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl approvedBy_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl history_div;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.HtmlControls.HtmlTable grdAttachments;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.FileUpload fileUploadControl;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnFilesNames;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnRecommendationId;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.HiddenField hdnApprovalAuthorityEmail;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSend;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnApprove;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnReject;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(MSARecommendationForm target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlmessage_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.message_div = @__ctrl;
            @__ctrl.ID = "message_div";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "messageDiv");
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n            "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlrecommendationNo_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.recommendationNo_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "recommendationNo_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.DropDownList @__BuildControlapprovalAuthority_ddl() {
            global::System.Web.UI.WebControls.DropDownList @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.DropDownList();
            this.approvalAuthority_ddl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "approvalAuthority_ddl";
            @__ctrl.CssClass = "form-control";
            @__ctrl.AutoPostBack = false;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControldescription_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.description_ta = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "description_ta";
            @__ctrl.Rows = 5;
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControltargetDate_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.targetDate_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "targetDate_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.PeopleEditor @__BuildControlresponsiblePerson_PeopleEditor() {
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.PeopleEditor();
            this.responsiblePerson_PeopleEditor = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "responsiblePerson_PeopleEditor";
            @__ctrl.AllowEmpty = false;
            @__ctrl.SelectionSet = "User";
            @__ctrl.AllowTypeIn = false;
            @__ctrl.Rows = 1;
            @__ctrl.MultiSelect = false;
            @__ctrl.ShowButtons = false;
            @__ctrl.CssClass = "disableControl";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlresponsibleDepartment_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.responsibleDepartment_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "responsibleDepartment_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlresponsibleSection_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.responsibleSection_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "responsibleSection_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control2() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Pending";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control3() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "In Progress";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.ListItem @__BuildControl__control4() {
            global::System.Web.UI.WebControls.ListItem @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.ListItem();
            @__ctrl.Text = "Completed";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlSelect @__BuildControlstatus_ddl() {
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlSelect();
            this.status_ddl = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "status_ddl";
            @__ctrl.Disabled = true;
            global::System.Web.UI.WebControls.ListItem @__ctrl1;
            @__ctrl1 = this.@__BuildControl__control2();
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(@__ctrl1);
            global::System.Web.UI.WebControls.ListItem @__ctrl2;
            @__ctrl2 = this.@__BuildControl__control3();
            @__parser.AddParsedSubObject(@__ctrl2);
            global::System.Web.UI.WebControls.ListItem @__ctrl3;
            @__ctrl3 = this.@__BuildControl__control4();
            @__parser.AddParsedSubObject(@__ctrl3);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlinjuryClassification_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.injuryClassification_tf = @__ctrl;
            @__ctrl.ID = "injuryClassification_tf";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControltypeOfVoilation_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.typeOfVoilation_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "typeOfVoilation_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlobservationCategoryA_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.observationCategoryA_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "observationCategoryA_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControllastStatement_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.lastStatement_ta = @__ctrl;
            @__ctrl.ID = "lastStatement_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTextArea @__BuildControlclosureJustification_ta() {
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTextArea();
            this.closureJustification_ta = @__ctrl;
            @__ctrl.ID = "closureJustification_ta";
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control");
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::Microsoft.SharePoint.WebControls.DateTimeControl @__BuildControlclosureDate_dtc() {
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl;
            @__ctrl = new global::Microsoft.SharePoint.WebControls.DateTimeControl();
            this.closureDate_dtc = @__ctrl;
            @__ctrl.ID = "closureDate_dtc";
            @__ctrl.CssClassTextBox = "form-control disableControl";
            @__ctrl.AutoPostBack = false;
            @__ctrl.UseTimeZoneAdjustment = false;
            @__ctrl.LocaleId = 2057;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlinitiatedBy_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.initiatedBy_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "initiatedBy_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlInputText @__BuildControlapprovedBy_tf() {
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlInputText();
            this.approvedBy_tf = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text");
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-control disableControl");
            @__ctrl.ID = "approvedBy_tf";
            @__ctrl.Disabled = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlapprovedBy_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.approvedBy_div = @__ctrl;
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("class", "form-group");
            @__ctrl.ID = "approvedBy_div";
            @__ctrl.Visible = false;
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                    <label>Approved By</label>\r\n               " +
                        "                     "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl1;
            @__ctrl1 = this.@__BuildControlapprovedBy_tf();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlGenericControl @__BuildControlhistory_div() {
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlGenericControl("div");
            this.history_div = @__ctrl;
            @__ctrl.ID = "history_div";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.HtmlControls.HtmlTable @__BuildControlgrdAttachments() {
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl;
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTable();
            this.grdAttachments = @__ctrl;
            @__ctrl.ID = "grdAttachments";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.FileUpload @__BuildControlfileUploadControl() {
            global::System.Web.UI.WebControls.FileUpload @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.FileUpload();
            this.fileUploadControl = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "fileUploadControl";
            @__ctrl.AllowMultiple = true;
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnFilesNames() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnFilesNames = @__ctrl;
            @__ctrl.ID = "hdnFilesNames";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnRecommendationId() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnRecommendationId = @__ctrl;
            @__ctrl.ID = "hdnRecommendationId";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.HiddenField @__BuildControlhdnApprovalAuthorityEmail() {
            global::System.Web.UI.WebControls.HiddenField @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.HiddenField();
            this.hdnApprovalAuthorityEmail = @__ctrl;
            @__ctrl.ID = "hdnApprovalAuthorityEmail";
            @__ctrl.Value = "";
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSend() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSend = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSend";
            @__ctrl.Text = "Send";
            @__ctrl.OnClientClick = "return isActionConfirmed(\'Send\');";
            @__ctrl.CssClass = "btnSend";
            @__ctrl.Click -= new System.EventHandler(this.btnSend_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSend_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnApprove() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnApprove = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnApprove";
            @__ctrl.Text = "Approve";
            @__ctrl.OnClientClick = "return isActionConfirmed(\'Approve\');";
            @__ctrl.CssClass = "btnApprove";
            @__ctrl.Click -= new System.EventHandler(this.btnApprove_Click);
            @__ctrl.Click += new System.EventHandler(this.btnApprove_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnReject() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnReject = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnReject";
            @__ctrl.Text = "Reject";
            @__ctrl.OnClientClick = "return isActionConfirmed(\'Reject\');";
            @__ctrl.CssClass = "btnReject";
            @__ctrl.Click -= new System.EventHandler(this.btnReject_Click);
            @__ctrl.Click += new System.EventHandler(this.btnReject_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnCancel() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnCancel = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnCancel";
            @__ctrl.Text = "Cancel";
            @__ctrl.OnClientClick = "return isActionConfirmed(\'Cancel\');";
            @__ctrl.CssClass = "btnCancel";
            @__ctrl.Click -= new System.EventHandler(this.btnCancel_Click);
            @__ctrl.Click += new System.EventHandler(this.btnCancel_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private global::System.Web.UI.WebControls.Button @__BuildControlbtnSave() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            this.btnSave = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this.Page);
            @__ctrl.ID = "btnSave";
            @__ctrl.Text = "Save";
            @__ctrl.OnClientClick = "return isActionConfirmed(\'Save\');";
            @__ctrl.CssClass = "btnSave";
            @__ctrl.Visible = false;
            @__ctrl.Click -= new System.EventHandler(this.btnSave_Click);
            @__ctrl.Click += new System.EventHandler(this.btnSave_Click);
            return @__ctrl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::SL.FG.FFL.WebParts.MSARecommendationForm.MSARecommendationForm @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"


<link href=""/_layouts/15/SL.FG.FFL/CSS/FGStyle.css"" rel=""stylesheet"" />

<style type=""text/css"">
    [id$=responsiblePerson_PeopleEditor_upLevelDiv] {
        border-radius: 5px !important;
        width: 100%;
        background-color: lightgray !important;
    }

    [id$=responsiblePerson_PeopleEditor_TopSpan] {
        border-radius: 5px !important;
        width: 100%;
        background-color: lightgray !important;
    }



</style>


<div class=""container"">
    <div class=""row"">
        <div class=""col-lg-12"">
            "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl1;
            @__ctrl1 = this.@__BuildControlmessage_div();
            @__parser.AddParsedSubObject(@__ctrl1);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
            <div class=""panel panel-success"">
                <div class=""panel-heading"">
                    <h5>MSA Recommendation Form</h5>
                </div>
                <div class=""panel-body"">
                    <div id=""printableArea"">
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Recommendation No</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl2;
            @__ctrl2 = this.@__BuildControlrecommendationNo_tf();
            @__parser.AddParsedSubObject(@__ctrl2);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Approval Authority</label>
                                    "));
            global::System.Web.UI.WebControls.DropDownList @__ctrl3;
            @__ctrl3 = this.@__BuildControlapprovalAuthority_ddl();
            @__parser.AddParsedSubObject(@__ctrl3);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                            </div>\r\n   " +
                        "                     </div>\r\n                        <div class=\"form-group\">\r\n " +
                        "                           <label>Description</label>\r\n                         " +
                        "   "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl4;
            @__ctrl4 = this.@__BuildControldescription_ta();
            @__parser.AddParsedSubObject(@__ctrl4);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Target Date</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl5;
            @__ctrl5 = this.@__BuildControltargetDate_tf();
            @__parser.AddParsedSubObject(@__ctrl5);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6 table-responsive"">
                                <label>Responsible Person<span style=""color: red"">&nbsp;*</span></label>
                                "));
            global::Microsoft.SharePoint.WebControls.PeopleEditor @__ctrl6;
            @__ctrl6 = this.@__BuildControlresponsiblePerson_PeopleEditor();
            @__parser.AddParsedSubObject(@__ctrl6);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>
                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Responsible Department</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl7;
            @__ctrl7 = this.@__BuildControlresponsibleDepartment_tf();
            @__parser.AddParsedSubObject(@__ctrl7);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Responsible Section</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl8;
            @__ctrl8 = this.@__BuildControlresponsibleSection_tf();
            @__parser.AddParsedSubObject(@__ctrl8);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                        </div>

                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Status</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlSelect @__ctrl9;
            @__ctrl9 = this.@__BuildControlstatus_ddl();
            @__parser.AddParsedSubObject(@__ctrl9);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Injury Classification</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl10;
            @__ctrl10 = this.@__BuildControlinjuryClassification_tf();
            @__parser.AddParsedSubObject(@__ctrl10);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                        </div>

                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Violation Category</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl11;
            @__ctrl11 = this.@__BuildControltypeOfVoilation_tf();
            @__parser.AddParsedSubObject(@__ctrl11);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                </div>
                            </div>
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Observation Category</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl12;
            @__ctrl12 = this.@__BuildControlobservationCategoryA_tf();
            @__parser.AddParsedSubObject(@__ctrl12);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                            </div>\r\n   " +
                        "                     </div>\r\n\r\n                        <div class=\"form-group\">\r" +
                        "\n                            <label>Last Comment</label>\r\n                      " +
                        "      "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl13;
            @__ctrl13 = this.@__BuildControllastStatement_ta();
            @__parser.AddParsedSubObject(@__ctrl13);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n\r\n                        <div class=\"form-grou" +
                        "p\">\r\n                            <label>Closure Justification<span style=\"color:" +
                        " red\">&nbsp;*</span></label>\r\n                            "));
            global::System.Web.UI.HtmlControls.HtmlTextArea @__ctrl14;
            @__ctrl14 = this.@__BuildControlclosureJustification_ta();
            @__parser.AddParsedSubObject(@__ctrl14);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                        </div>

                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Closure Date</label>
                                    <div class=""form-group"">
                                        "));
            global::Microsoft.SharePoint.WebControls.DateTimeControl @__ctrl15;
            @__ctrl15 = this.@__BuildControlclosureDate_dtc();
            @__parser.AddParsedSubObject(@__ctrl15);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class=""form-group row"">
                            <div class=""col-lg-6"">
                                <div class=""form-group"">
                                    <label>Assigned By</label>
                                    "));
            global::System.Web.UI.HtmlControls.HtmlInputText @__ctrl16;
            @__ctrl16 = this.@__BuildControlinitiatedBy_tf();
            @__parser.AddParsedSubObject(@__ctrl16);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                </div>\r\n                            </div>\r\n   " +
                        "                         <div class=\"col-lg-6\">\r\n                               " +
                        " "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl17;
            @__ctrl17 = this.@__BuildControlapprovedBy_div();
            @__parser.AddParsedSubObject(@__ctrl17);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl(@"
                            </div>
                        </div>

                        <div class=""form-group"" id=""viewHistory_div"" style=""display: none;"">
                            <p class=""dataHeading"">Closure Justification History</p>
                            "));
            global::System.Web.UI.HtmlControls.HtmlGenericControl @__ctrl18;
            @__ctrl18 = this.@__BuildControlhistory_div();
            @__parser.AddParsedSubObject(@__ctrl18);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                    </div>\r\n                   " +
                        " <div class=\"form-group\">\r\n                        <label>Attachment</label>\r\n  " +
                        "                      <div>\r\n                            "));
            global::System.Web.UI.HtmlControls.HtmlTable @__ctrl19;
            @__ctrl19 = this.@__BuildControlgrdAttachments();
            @__parser.AddParsedSubObject(@__ctrl19);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                        </div>\r\n                        "));
            global::System.Web.UI.WebControls.FileUpload @__ctrl20;
            @__ctrl20 = this.@__BuildControlfileUploadControl();
            @__parser.AddParsedSubObject(@__ctrl20);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    </div>\r\n                </div>\r\n\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl21;
            @__ctrl21 = this.@__BuildControlhdnFilesNames();
            @__parser.AddParsedSubObject(@__ctrl21);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl22;
            @__ctrl22 = this.@__BuildControlhdnRecommendationId();
            @__parser.AddParsedSubObject(@__ctrl22);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                "));
            global::System.Web.UI.WebControls.HiddenField @__ctrl23;
            @__ctrl23 = this.@__BuildControlhdnApprovalAuthorityEmail();
            @__parser.AddParsedSubObject(@__ctrl23);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n                <div class=\"form-group pull-right\" style=\"margin-top: 15px;\">" +
                        "\r\n                    <input id=\"print_btn\" value=\"Print\" type=\"button\" class=\"b" +
                        "tnPrint\" onclick=\"printContent();\" />\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl24;
            @__ctrl24 = this.@__BuildControlbtnSend();
            @__parser.AddParsedSubObject(@__ctrl24);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl25;
            @__ctrl25 = this.@__BuildControlbtnApprove();
            @__parser.AddParsedSubObject(@__ctrl25);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl26;
            @__ctrl26 = this.@__BuildControlbtnReject();
            @__parser.AddParsedSubObject(@__ctrl26);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl27;
            @__ctrl27 = this.@__BuildControlbtnCancel();
            @__parser.AddParsedSubObject(@__ctrl27);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                    <input id=\"viewHistory_btn\" value=\"View History\" type=\"butt" +
                        "on\" class=\"btnViewHistory\" />\r\n                    "));
            global::System.Web.UI.WebControls.Button @__ctrl28;
            @__ctrl28 = this.@__BuildControlbtnSave();
            @__parser.AddParsedSubObject(@__ctrl28);
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r" +
                        "\n\r\n<script src=\"/_layouts/15/SL.FG.FFL/Scripts/jQuery.js\"></script>\r\n\r\n\r\n<script" +
                        " type=\"text/javascript\">\r\n    function isActionConfirmed(action) {\r\n\r\n        va" +
                        "r message = \"MSA Recommendation: Are you sure you want to perform this action?\";" +
                        "\r\n        var flag = false;\r\n\r\n        if (typeof action != \'undefined\' && actio" +
                        "n != null && action != \"\") {\r\n            if (action == \"Save\") {\r\n             " +
                        "   message = \"Do you want to Save?\";\r\n                flag = true;\r\n            " +
                        "}\r\n            else if (action == \"Approve\") {\r\n                message = \"Do yo" +
                        "u want to Approve?\";\r\n                flag = true;\r\n            }\r\n            e" +
                        "lse if (action == \"Reject\") {\r\n                message = \"Do you want to Reject?" +
                        "\";\r\n                flag = true;\r\n            }\r\n            else if (action == " +
                        "\"Send\") {\r\n                message = \"Do you want to Send?\";\r\n                fl" +
                        "ag = true;\r\n            }\r\n        }\r\n\r\n        var confirm = window.confirm(mes" +
                        "sage);\r\n        if (!confirm) {\r\n            return false;\r\n        }\r\n\r\n       " +
                        " if (flag == true && $(\'[id$=closureJustification_ta]\').val() == \"\")\r\n        {\r" +
                        "\n            alert(\"Please Provide value for the required fields\");\r\n           " +
                        " $(\'[id$=closureJustification_ta]\').focus();\r\n            return false;\r\n       " +
                        " }\r\n\r\n        if (flag == true && $(\'[id$=approvalAuthority_ddl] option:selected" +
                        "\').val() == \"0\") {\r\n            alert(\"Please Provide value for the required fie" +
                        "lds\");\r\n            $(\'[id$=approvalAuthority_ddl]\').focus();\r\n            retur" +
                        "n false;\r\n        }\r\n        return true;\r\n    }\r\n\r\n    function printContent() " +
                        "{\r\n        var data = $(\"#printableArea\").html();\r\n\r\n        var popupWindow = w" +
                        "indow.open(\'MSA Recommendation\', \'printwin\', \'left=10,top=10,width=1000,height=1" +
                        "000\');\r\n        popupWindow.document.write(\'<HTML>\\n<HEAD>\\n\');\r\n        popupWi" +
                        "ndow.document.write(\'<TITLE>MSA Recommendation Form</TITLE>\\n\');\r\n        popupW" +
                        "indow.document.write(\'<URL></URL>\\n\');\r\n        popupWindow.document.write(\"<lin" +
                        "k href=\'/_layouts/15/SL.FG.FFL/CSS/BS3/bootstrap3.min.css\' rel=\'stylesheet\'/>\\n\"" +
                        ");\r\n        popupWindow.document.write(\"<link href=\'/_layouts/15/SL.FG.FFL/CSS/F" +
                        "GStyle.css\' rel=\'stylesheet\'/>\\n\");\r\n        popupWindow.document.write(\'<script" +
                        ">\\n\');\r\n        popupWindow.document.write(\'function print_win(){\\n\');\r\n        " +
                        "popupWindow.document.write(\'\\n window.print();\\n\');\r\n        popupWindow.documen" +
                        "t.write(\'}\\n\');\r\n        popupWindow.document.write(\'<\\/script>\\n\');\r\n        po" +
                        "pupWindow.document.write(\'</HEAD>\\n\');\r\n        popupWindow.document.write(\'<BOD" +
                        "Y onload=\"print_win()\" style=\"margin: 10px 10px 10px 10px; overflow:scroll;\">\\n\'" +
                        ");\r\n        popupWindow.document.write(data);\r\n        popupWindow.document.writ" +
                        "e(\'</BODY>\\n\');\r\n        popupWindow.document.write(\'</HTML>\\n\');\r\n        popup" +
                        "Window.document.close();\r\n    }\r\n\r\n    $(document).ready(function () {\r\n\r\n      " +
                        "  $(\'[id$=viewHistory_btn]\').on(\'click\', function () {\r\n            $(\'[id$=view" +
                        "History_div]\').toggle();\r\n        });\r\n\r\n        $(\'span.removeLink\').on(\'click\'" +
                        ", function () {\r\n            var par = $(this).closest(\'tr\');\r\n            var f" +
                        "ileName = par.find(\'span.fileName\');\r\n\r\n            if (fileName != \'undefined\' " +
                        "&& fileName != \"\" && fileName != null) {\r\n                var filenames = $(\'[id" +
                        "$=hdnFilesNames]\').val();\r\n                filenames += \"~\" + fileName.text();\r\n" +
                        "\r\n                $(\'[id$=hdnFilesNames]\').val(filenames);\r\n            }\r\n     " +
                        "       par.remove();\r\n        });\r\n\r\n        // Capturing when the user modifies" +
                        " a field\r\n        var warnMessage = \'You have unsaved changes on this page!\';\r\n " +
                        "       var formModified = new Boolean();\r\n        formModified = false;\r\n       " +
                        " $(\'input:not(:button,:submit),textarea,select\').on(\'change\', function () {\r\n   " +
                        "         formModified = true;\r\n        });\r\n        // Checking if the user has " +
                        "modified the form upon closing window\r\n        $(\'input:submit\').on(\'click\', fun" +
                        "ction (e) {\r\n            formModified = false;\r\n        });\r\n        window.onbe" +
                        "foreunload = function () {\r\n            if (formModified != false) return warnMe" +
                        "ssage;\r\n        }\r\n\r\n        $(\'.panel-collapse\').collapse(\'show\');\r\n\r\n        $" +
                        "(\'[id$=responsiblePerson_PeopleEditor_downlevelTextBox]\').attr(\"disabled\", \"disa" +
                        "bled\");\r\n    });\r\n</script>\r\n"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
